
[build]
target = "i686-firmware.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[profile.dev]
opt-level = "z"
lto = true
debug = false

[profile.release]
opt-level = "z"
lto = true
debug = false
codegen-units = 1
