
[build]
target = "i686-firmware.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[profile.dev]
opt-level = "z"
lto = true
debug = false

[profile.release]
opt-level = "z"
lto = true
debug = false
codegen-units = 1

[workspace.package]
version = "0.1.0"
edition = "2024"
