[package]
name = "flashrom_monitor"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
flashrom_init86 = { path = "../flashrom_init86" }
x86 = "0.52.0"
monitor = { path = "../monitor" }
common = { path = "../common" }
