[workspace]
resolver = "2"

members = [
  "d945gclf_sdram",
  "sdram_helloworld",
  "sdram_monitor",
  "common",
  "init86",
]

[profile.release]
panic = "abort"
opt-level = "z"

[profile.dev]
panic = "abort"

